### ISSUE TITLE
SS3.3.2 changes .ui-tabs li margins

### ISSUE THREAD

**Issue by mspacemedia** [praxisnetau/silverstripe-moderno-admin#11]
``` css
.cms-content-fields .ui-tabs-nav li {
  margin: 0 auto !important;
}
```

Is required to get nicely spaced tab elements.
